baseURL = "https://kaifalu.com/"
relativeURLs = true
languageCode = "en-us"
title = "kaifalu"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  recent_copy=""
  favicon = ""
  site_logo = "https://static.kaifalu.com/static/images/1_WgYfacPv_template.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  #twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = "https://github.com/bitmyth"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5
  custom_css = ["css/mystyles.css"]
  commentoEnable = true
